GET http://localhost:5000/api/movies

###

GET http://localhost:5000/api/movie/60292ad69025d92f2f59663d

### 
POST http://localhost:5000/api/movie
Content-Type: application/json

{  
        "name": "Batman",
        "time": "2.3 hrs",
        "rating": 9.0
}


###

